FROM golang:1.18-alpine

RUN apk add --no-cache --update curl \
    bash \
    grep \
    sed \
    jq \
    ca-certificates \
    openssl \
    git \
	make \
	gcc \
	musl-dev

WORKDIR /app

COPY go.* .
RUN go mod tidy

COPY . .

RUN make deps

EXPOSE 9002
EXPOSE 3002

CMD ["gin","--appPort", "9002", "--port", "3002", "--immediate", "run", "server"]
